//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkAutoPhotoUploader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VkAutoPhotoUploader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.vk.com/method/{0}&amp;access_token={1}.
        /// </summary>
        public static string ApiVkUrl {
            get {
                return ResourceManager.GetString("ApiVkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.createAlbum?title={0}&amp;group_id={1}&amp;upload_by_admins_only=1.
        /// </summary>
        public static string CreateAlbumUrl {
            get {
                return ResourceManager.GetString("CreateAlbumUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.getUploadServer?album_id={0}&amp;group_id={1}.
        /// </summary>
        public static string GetUploadServerUrl {
            get {
                return ResourceManager.GetString("GetUploadServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://oauth.vk.com/authorize?client_id={0}&amp;scope=397316&amp;redirect_uri=https://oauth.vk.com/blank.html&amp;display=popup&amp;v=5.26&amp;response_type=token.
        /// </summary>
        public static string OauthUrl {
            get {
                return ResourceManager.GetString("OauthUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App_Data/Products.json.
        /// </summary>
        public static string PathProductsFile {
            get {
                return ResourceManager.GetString("PathProductsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App_Data/AppSettings.json.
        /// </summary>
        public static string PathSettingsFile {
            get {
                return ResourceManager.GetString("PathSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\n\nЦена: {1}\n\n{2}.
        /// </summary>
        public static string PhotoDescription {
            get {
                return ResourceManager.GetString("PhotoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.save?album_id={0}&amp;group_id={1}&amp;server={2}&amp;photos_list={3}&amp;hash={4}&amp;caption={5}.
        /// </summary>
        public static string SavePhotoUrl {
            get {
                return ResourceManager.GetString("SavePhotoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/katalog?&amp;items_per_page=150&amp;page=.
        /// </summary>
        public static string SiteUrlForWebParser {
            get {
                return ResourceManager.GetString("SiteUrlForWebParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code = {0}, Message = {1}.
        /// </summary>
        public static string VkExceptionMessage {
            get {
                return ResourceManager.GetString("VkExceptionMessage", resourceCulture);
            }
        }
    }
}
